### ISSUE TITLE
Integrity constraint violation: 1048 Column 'fieldLayoutId' cannot be null

### ISSUE THREAD

**Issue by dillonbailey** [Anubarak/craft-relabel#11]
**Description**
Running a new Craft install with a project.yml that includes settings from `relabel` produces the following error during the install database migration step:

```
Exception: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'fieldLayoutId' cannot be null
The SQL being executed was: INSERT INTO `relabel` (`uid`, `fieldId`, `fieldLayoutId`, `instructions`, `name`, `dateCreated`, `dateUpdated`) VALUES ('df7a1cf5-4ef3-4c6f-8991-01b188b9bf7f', 62, NULL, '', 'Content', '2019-10-27 14:20:55', '2019-10-27 14:20:55') (/home/vagrant/code/proejct/craft/vendor/yiisoft/yii2/db/Schema.php:664)
```

Example entry from project.yml looks like:
```
relabel:
  016043c5-bb96-46d6-b148-811900a56f14:
    field: 686a3021-a8b1-4213-b8b5-4e4886823ed8
    fieldLayout: e9270c63-c469-418f-b352-5bf4d56b9cea
    instructions: ''
    name: 'Show Facebook on page'
```

MySQL v5.7
PHP v7.2
Craft v3.2.10
